name: Synchronize Development
on:
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sync to S3
        run : |
          if(${GITHUB_BRANCH##*/}=="development") ? echo "${GITHUB_BRANCH##*/}" 
          : if(${GITHUB_BRANCH##*/}=="staging") ? echo "${GITHUB_BRANCH##*/}"
