name: Manual-Actions-Workflow-Dev
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Purge all files from Imgix main
        if: ${{ github.ref == 'refs/heads/main' }}
        run:
           echo "Test Successfull in main"
           
      - name: Purge all files from Imgix Dev
        if: ${{ github.ref == 'refs/heads/main/development' }}
        run:
           echo "Test Successfull in dev"
