name: Synchronize Development
on:
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Testing
        run : |
          if: (${GITHUB_BRANCH##*/}=='development') 
           echo "${GITHUB_BRANCH##*/}" 
         
